from groq import Groq

from app.config import settings


class GroqService:
    """
    Service responsible for interacting with the Groq API.
    """

    def __init__(self):
        self.client = Groq(api_key=settings.GROQ_API_KEY)

    def generate_sql(self, prompt: str) -> str:
        """
        Sends the prompt to the Groq API and returns the generated SQL.

        Args:
            prompt (str): Prompt created by prompt.py

        Returns:
            str: SQL query generated by the model.
        """

        try:
            response = self.client.chat.completions.create(
                model=settings.MODEL_NAME,
                temperature=settings.TEMPERATURE,
                max_completion_tokens=settings.MAX_TOKENS,
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are an expert SQL developer. "
                            "Always return ONLY SQL."
                        ),
                    },
                    {
                        "role": "user",
                        "content": prompt,
                    },
                ],
            )

            sql = response.choices[0].message.content.strip()

            return sql

        except Exception as e:
            raise Exception(f"Groq API Error: {str(e)}")


# Singleton instance
groq_service = GroqService()